// Generated by Dagger (https://dagger.dev).
package abdulmanov.eduard.timetable.presentation.events.onetimeclass;

import androidx.lifecycle.ViewModelProvider;
import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class OneTimeClassFragment_MembersInjector implements MembersInjector<OneTimeClassFragment> {
  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  public OneTimeClassFragment_MembersInjector(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    this.viewModelFactoryProvider = viewModelFactoryProvider;
  }

  public static MembersInjector<OneTimeClassFragment> create(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    return new OneTimeClassFragment_MembersInjector(viewModelFactoryProvider);
  }

  @Override
  public void injectMembers(OneTimeClassFragment instance) {
    injectViewModelFactory(instance, viewModelFactoryProvider.get());
  }

  @InjectedFieldSignature("abdulmanov.eduard.timetable.presentation.events.onetimeclass.OneTimeClassFragment.viewModelFactory")
  public static void injectViewModelFactory(OneTimeClassFragment instance,
      ViewModelProvider.Factory viewModelFactory) {
    instance.viewModelFactory = viewModelFactory;
  }
}
