// Generated by Dagger (https://dagger.dev).
package abdulmanov.eduard.timetable.presentation.events.note;

import androidx.lifecycle.ViewModelProvider;
import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class NoteFragment_MembersInjector implements MembersInjector<NoteFragment> {
  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  public NoteFragment_MembersInjector(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    this.viewModelFactoryProvider = viewModelFactoryProvider;
  }

  public static MembersInjector<NoteFragment> create(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    return new NoteFragment_MembersInjector(viewModelFactoryProvider);
  }

  @Override
  public void injectMembers(NoteFragment instance) {
    injectViewModelFactory(instance, viewModelFactoryProvider.get());
  }

  @InjectedFieldSignature("abdulmanov.eduard.timetable.presentation.events.note.NoteFragment.viewModelFactory")
  public static void injectViewModelFactory(NoteFragment instance,
      ViewModelProvider.Factory viewModelFactory) {
    instance.viewModelFactory = viewModelFactory;
  }
}
