// Generated by Dagger (https://dagger.dev).
package abdulmanov.eduard.timetable.presentation.events.note;

import com.github.terrakok.cicerone.Router;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class NoteViewModel_Factory implements Factory<NoteViewModel> {
  private final Provider<Router> routerProvider;

  public NoteViewModel_Factory(Provider<Router> routerProvider) {
    this.routerProvider = routerProvider;
  }

  @Override
  public NoteViewModel get() {
    return newInstance(routerProvider.get());
  }

  public static NoteViewModel_Factory create(Provider<Router> routerProvider) {
    return new NoteViewModel_Factory(routerProvider);
  }

  public static NoteViewModel newInstance(Router router) {
    return new NoteViewModel(router);
  }
}
